### ISSUE TITLE
f touches quotation marks

### ISSUE THREAD

**Issue by lwchkg** [georgd/EB-Garamond#102]
As title. I would appreciate if some improvement can be done to the rendering of ‘if’ and “if”. Thanks!

Current situation:
![soffice bin_2018-09-13_14-32-10](https://user-images.githubusercontent.com/4113719/45470888-ebc3f980-b761-11e8-8cfc-24f23f5c55ff.png)

**Comment by georgd** [comment]
This shouldn’t happen usually, if contextual alternatives are switched on.
