### ISSUE TITLE
Enclosed numbers and letters

### ISSUE THREAD

**Issue by stone-zeng** [georgd/EB-Garamond#105]
Recently, I have added enclosed (circled) numbers and letters into the fork Garamon-Math. If it's possible, I hope these symbols can be added into the main EB Garamond repo.

Here is a demo:

![image](https://user-images.githubusercontent.com/18233088/47209411-df673800-d3c2-11e8-9635-7dc7096c56af.png)

Details can be checked in the [Garamon-Math](https://github.com/YuanshengZhao/Garamond-Math) repo. Is there any problems? For example, are they consistent with the design of the normal digits/letters?

If you enjoy them, I can create a PR to add them.

**Comment by georgd** [comment]
Yes, please do create a PR. Thank you!
