### ISSUE TITLE
Some problems with fontspec and xelatex under windows

### ISSUE THREAD

**Issue by maser111** [georgd/EB-Garamond#106]
I'm using EB Garamond on Windows with MikTeX 2.9 and fontspec with xelatex. I've updated the package downloaded with MikTex (package of 5 Dec 2018). Before the update, the output have a well rendered font with oldstyle numbers and Q.long by default. After the update, the font seems the default Garamond by windows. 

This is  my short test.

```
\documentclass{book}

%\usepackage[english,italian]{babel}
\usepackage[utf8]{inputenc}

\usepackage{fontspec}
\setmainfont{EB Garamond}

\usepackage{lipsum}

%%%% STARTING DOCUMENT

\begin{document}

\chapter{Lorem Ipsum}

0123456789 Qui Pro Quo.\par

\lipsum[1]\par
\lipsum[2]\par
\lipsum[3]\par
\lipsum[4]\par

\end{document}
```
What I'm doing wrong?

**Comment by maser111** [comment]
I have recreated the test file under a linux box (test - ok.pdf) and the file produced after the update on windows (test - not ok.pdf)

[test - not ok.pdf](https://github.com/georgd/EB-Garamond/files/2684911/test.-.not.ok.pdf)
[test - ok.pdf](https://github.com/georgd/EB-Garamond/files/2684913/test.-.ok.pdf)

**Comment by vronizor** [comment]
The long Q is located within a different stylistic set (ss) of the OpenType features, specifically in ss6. You can go through the fonts feature using [FontDrop](https://fontdrop.info/). Just drag/drop the `EBGaramond-Regular.otf` file there and go to the OT tab to see all the features of the fonts.

Going back to your example, changing the `setmainfont` options did it for me:

```
\setmainfont{EB Garamond}[StylisticSet=6]
```
See section 3.1.13 on page 45 of the [fontspec manual](https://osl.ugr.es/CTAN/macros/latex/contrib/fontspec/fontspec.pdf).
