### ISSUE TITLE
Missing Glyphs in EBGaramond-Initials

### ISSUE THREAD

**Issue by tjt263** [georgd/EB-Garamond#109]
Why are there so many missing glyphs for this font?
Were they not in the original scans, or do you just need someone to draw them?
I mean, the characters exist in the regular styles. Are you just missing the ornaments?
It's been around a while, let us know gow we can help get it finished.

**Comment by rixx** [comment]
In case anybody is tempted by the beautiful initials, this is the current state of the project (which sadly seems somewhat abandoned).
![Screenshot_2019-11-16 Projects](https://user-images.githubusercontent.com/2657547/68985793-7f3b0380-0819-11ea-835c-69b7214d67d2.png)

**Comment by doctorlard** [comment]
I'd love to help, but I have no idea how to even start.

**Comment by mikkelee** [comment]
Georg Duffner writes on the [design plan](http://www.georgduffner.at/ebgaramond/design.html): "Additionally, fonts providing initials based on renaissance designs will be provided. The current source for these initials is the [Bible de Genève](http://www.bvh.univ-tours.fr/Consult/index.asp?numtable=B372615206_18229&numfiche=571&mode=1&offset=15&ecran=0&url=) as printed in 1564 in Lyon, France."

It appears to contain many still missing initials. I went through Genesis and found these:

* C: [Genesis 5](http://www.bvh.univ-tours.fr/Consult/consult.asp?numtable=B372615206%5F18229&numfiche=571&mode=1&ecran=0&offset=15&index=19)
* E: [Genesis 7](http://www.bvh.univ-tours.fr/Consult/consult.asp?numtable=B372615206%5F18229&numfiche=571&mode=1&ecran=0&offset=15&index=21), [Genesis 9](http://www.bvh.univ-tours.fr/Consult/consult.asp?numtable=B372615206%5F18229&numfiche=571&mode=1&ecran=0&offset=15&index=23), [Genesis 19](http://www.bvh.univ-tours.fr/Consult/consult.asp?numtable=B372615206%5F18229&numfiche=571&mode=1&ecran=0&offset=15&index=32), [Genesis 20](http://www.bvh.univ-tours.fr/Consult/consult.asp?numtable=B372615206%5F18229&numfiche=571&mode=1&ecran=0&offset=15&index=33), [Genesis 22](http://www.bvh.univ-tours.fr/Consult/consult.asp?numtable=B372615206%5F18229&numfiche=571&mode=1&ecran=0&offset=15&index=35), [Genesis 24](http://www.bvh.univ-tours.fr/Consult/consult.asp?numtable=B372615206%5F18229&numfiche=571&mode=1&ecran=0&offset=15&index=37), and several more
* I: [Genesis 38](http://www.bvh.univ-tours.fr/Consult/consult.asp?numtable=B372615206%5F18229&numfiche=571&mode=1&ecran=0&offset=15&index=56), [Genesis 47](http://www.bvh.univ-tours.fr/Consult/consult.asp?numtable=B372615206%5F18229&numfiche=571&mode=1&ecran=0&offset=15&index=68)
* M: [Genesis 41](http://www.bvh.univ-tours.fr/Consult/consult.asp?numtable=B372615206%5F18229&numfiche=571&mode=1&ecran=0&offset=15&index=59)
* S: [Genesis 10](http://www.bvh.univ-tours.fr/Consult/consult.asp?numtable=B372615206%5F18229&numfiche=571&mode=1&ecran=0&offset=15&index=24), [Genesis 36](http://www.bvh.univ-tours.fr/Consult/consult.asp?numtable=B372615206%5F18229&numfiche=571&mode=1&ecran=0&offset=15&index=54)

There are also some much larger initials, see for instance D in [Genesis 1](http://www.bvh.univ-tours.fr/Consult/consult.asp?numfiche=571&index=15&numtable=B372615206_18229&mode=1&ecran=0) and C in [Exodus 1](http://www.bvh.univ-tours.fr/Consult/consult.asp?numtable=B372615206%5F18229&numfiche=571&mode=1&ecran=0&offset=15&index=73)

The Genève initials would need to cleaned up and redrawn as vectors to be included in the font.

**Comment by mikkelee** [comment]
There, that's the OT :)

**Comment by mikkelee** [comment]
See also this, the Bibliothèque has separated out the lettrines in a bit higher resolution than the page scans themselves:

http://www.bvh.univ-tours.fr/Consult/imgcherche.asp?numfiche=571&numtable=B372615206_18229&typeimg=Lettrine&position=1&mode=1&ecran=0

**Comment by mikkelee** [comment]
And another of their sites, with alphabetically sorted lettrines:

http://www.bvh.univ-tours.fr/batyr/beta/notice_libraire.php?Libraire=5

Note that they haven't registered any other examples than the ones I found previously. It appears that there were no lettrines for the letters JKUWXYZ...

**Comment by lutetiensis** [comment]
- The font lacks ```BCEHIJKMPRSUVWXYZ``` initials.
- ```BCEHIMPRSVXY``` _Fill2_ (letters) can be found in the [EB specimen](http://image.linotype.com/files/pdf/specimen.pdf); ```JKUWZ``` are missing.
    - ```BCEHIMPRSVXY``` must be extracted.
    - ```JKUWZ``` must be drawn.
- ```BCEHIMPRSV``` _Fill1_ (decorations) can be found in the lettrines of the [Bibliothèques Virtuelles Humanistes](http://www.bvh.univ-tours.fr/batyr/beta/notice_libraire.php?Libraire=5); ```JKUWXYZ``` are missing.
    - ```BCEHIMPRSV``` must be chosen (since several variants exist), then extracted.
    - ```JKUWXYZ``` must be drawn.
- Finally, _Fill1_ and _Fill2_ must be merged to generate the _EB Garamond_ Initials font.

I will give it a try, as I know a little of everything that is needed here.

Let's start with a lettrine for which both the letter and the decoration exist, I suggest **V**.

Three variants exist: [9737](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=9737), [9777](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=9777) et [10339](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=10339). Which ones do you all prefer? I think 9737 is the one that matches the others best.

**Comment by mikkelee** [comment]
Agreed on 9737

**Comment by lutetiensis** [comment]
After about three hours of work, here is what I could do:

<img width="775" src="https://user-images.githubusercontent.com/66195380/103460246-13fe0a80-4d15-11eb-80a3-89f2d2835724.png">

It will require **a lot** of cleanup before looking good, but what do you all think so far?

If we agree on this direction, I will finish it, then look at integrating this letter (bba8267b?) and finally generate an OTF we can all play with.

@mikkelee I forgot to thank you for your ample research!

**Comment by mikkelee** [comment]
Looks like a good base to me, but as you say, it requires much cleanup. I would help, but I am slow and, to be honest, pretty bad at drawing Bézier curves. So I figured doing some research was the best way I could contribute hehe.

**Comment by lutetiensis** [comment]
I just succeeded in building an OTF shipping my character (V) and MacOS is happy with it. Quite encouraging for a first day! Now I need to work on those paths... *sigh*

<img width="795" src="https://user-images.githubusercontent.com/66195380/103469032-ff932f80-4d5f-11eb-9d74-e39a2204dab7.png">

**Comment by bt2901** [comment]
What does https://github.com/georgd/EB-Garamond/commit/bba8267ba6400e5ce0cbee25183d480a808c4b41 by @georgd do, exactly? It appears that this commit adds `D` glyph, but isn't the initial D already in the font? Is it about adding another variation?

**Comment by lutetiensis** [comment]
Here is V. Let me know what you think. I can make tiny corrections, but if you are happy I will start a branch for a potential PR.

![V](https://user-images.githubusercontent.com/66195380/103575399-f7f39800-4ed1-11eb-9c42-97e73e473b4e.png)

I will do the [H initial](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=10445) next.

**Comment by georgd** [comment]
@lutetiensis thanks for your great initiative! I like the V and I surely will merge it. As for the H, I already have done it quite some time ago but wasn't able to merge it for various reasons back then. I'll do it later this week if you don't mind.

**Comment by lutetiensis** [comment]
> @lutetiensis thanks for your great initiative! I like the V

It's great to hear from you @georgd! You liking it means a lot to me!

> I surely will merge it.

Do you have a nice way to convert glyph to SVG? I looked at different ways ([like this](https://github.com/fontforge/fontforge/blob/master/pycontrib/svg2sfd.py))... and ultimately wrote this piece of code:

```diff
diff --git a/tools/makefont.py b/tools/makefont.py
index c1ab91c2d..ea46a2eaf 100644
--- a/tools/makefont.py
+++ b/tools/makefont.py
@@ -3,6 +3,7 @@
 # invoked by the Makefile
 
 from __future__ import absolute_import, print_function, unicode_literals
+import glob
 import os
 import re
 import sys
@@ -57,6 +58,10 @@ font.selection.all()
 font.removeOverlap()
 font.autoHint()
 
+for svg in glob.glob(args.input + "/*svg"):
+    letter = os.path.splitext(os.path.basename(svg))[0]
+    font.createMappedChar(letter).importOutlines(svg)
+
 if args.reloadgpos:
     for lookup in font.gpos_lookups:
         font.removeLookup(lookup)
-- 
2.30.0
```

I could also send you the SVGs, but might as well, I'd rather write a clean patch that you can one-click merge.

> As for the H, I already have done it quite some time ago but wasn't able to merge it for various reasons back then. I'll do it later this week if you don't mind.

I surely don't! I noticed the N isn't quite finished, so I could maybe refresh it? Or work on the C? Do you have other letters ready in your branches? Given the time it takes, I would hate doing something you have already done! ;)

And since you're here: congratulations, and thanks for your tremendous work. I have been a user for EB G for years!

**Comment by georgd** [comment]
> > @lutetiensis thanks for your great initiative! I like the V
> 
> It's great to hear from you @georgd! You liking it means a lot to me!
> 
> > I surely will merge it.
> 
> Do you have a nice way to convert SVG to glyph? I looked at different ways ([like this](https://github.com/fontforge/fontforge/blob/master/pycontrib/svg2sfd.py))... and ultimately wrote this piece of code:

No, I don't. If that works, it'll be better than anything I could come up in a reasonable amount of time.

> I could also send you the SVGs, but might as well, I'd rather write a clean patch that you can one-click merge.
> 
> > As for the H, I already have done it quite some time ago but wasn't able to merge it for various reasons back then. I'll do it later this week if you don't mind.
> 
> I surely don't! I noticed the N isn't quite finished, so I could maybe refresh it? Or work on the C? Do you have other letters ready in your branches? Given the time it takes, I would hate doing something you have already done! ;)
> 
> And since you're here: congratulations, and thanks for your tremendous work. I have been a user of EB G for years!

Thank you!

> Edit: waiiiit a minute. What is `-Lettrines`? Is it the same as `-Initials` but including characters that haven't been cleaned yet?

Shame on me that I forgot about that. I'm really sorry. I wrote it down in the Readme, else I'd be very puzzled right now. Yes, the `-Lettrines` contains automatic tracings of the initials I could find in the _Bible de Génève_. In most of them I cleaned up the letter from inkless spots but not more. So, right, it's probably the best place to cotinue the work. Looking at your V: I like it much better than my choice :), a PR is definitely very welcome!

**Comment by lutetiensis** [comment]
> No, I don't. If that works, it'll be better than anything I could come up in a reasonable amount of time.

Alright then.

> Shame on me that I forgot about that. I'm really sorry. I wrote it down in the Readme, else I'd be very puzzled right now. Yes, the `-Lettrines` contains automatic tracings of the initials I could find in the _Bible de Génève_. In most of them I cleaned up the letter from inkless spots but not more. So, right, it's probably the best place to cotinue the work. Looking at your V: I like it much better than my choice :), a PR is definitely very welcome!

No worry, it's actually a good surprise! Next steps for me: submit a PR for V, and start working on C.

**Comment by astoeriko** [comment]
I would also love to contribute by converting one or several (depending on how long it takes me) of the pictures to SVG. I would need some help regarding the steps after that as I have never worked with fonts before.
I would like to start with the M and then S.

**Comment by lutetiensis** [comment]
Great! @astoeriko

For now you can prepare the SVG files: one for ```Initials Fill 1```, one for ```Initials Fill 2``` and one for ```Initials``` that is the **exact** combination of the previous ones (@georgd Do we agree on 1000x1000 for the SVGs?).

By then, I will have shot a PR for V that you can copy. You don't need to know anything about fonts, the build system will take care of everything for you.

So H is @georgd's, M and S are @astoeriko's, C and N are @lutetiensis'!

I think I am going to start a new ticket...

**Comment by georgd** [comment]
> Great! @astoeriko
> 
> For now you can prepare the SVG files: one for `Initials Fill 1`, one for `Initials Fill 2` and one for `Initials` that is the **exact** combination of the previous ones (@georgd Do we agree on 1000x1000 for the SVGs?).

Yes, that's fine.

> By then, I will have shot a PR for V that you can copy. You don't need to know anything about fonts, the build system will take care of everything for you.

Still, we'll have to check if the curves are valid after merging.

**Comment by anotherishi** [comment]
Check this out 
https://turntrout.com/static/styles/fonts/EBGaramond/EBGaramond-InitialsF1.woff2
https://turntrout.com/static/styles/fonts/EBGaramond/EBGaramond-InitialsF2.woff2

Thanks to Alex Turner 
https://turntrout.com/design#dropcaps
