### ISSUE TITLE
Creating remaining Initials

### ISSUE THREAD

**Issue by lutetiensis** [georgd/EB-Garamond#115]
Note: https://github.com/georgd/EB-Garamond/issues/115#issuecomment-787122803.

This ticket spawns from #109. It keeps tracks of the current efforts to provide missing initials in EB Garamond.

Here are the steps to add a new initial:
1. Create three SVG files for ```Initials-Fill1``` (the decorations), ```Initials-Fill2``` (the actual letter) and ```Initials``` (an exact combination of the previous ones). The glyphs must be 1000x1000 and fully vectorial.
2. Name them ```X.svg``` (```X``` being the letter, eg. ```V.svg```) and put them in the following directories: ```SFD/EBGaramond-{Initials,InitialsF1,InitialsF2}.sfdir/``` (0bed85b4).
3. Run ```make``` and check the output.

Let me know if you want to volunteer for any TBD task.

| Letter | Status | Source | Owner |
|:-: | - | :-: | :-: |
|A| Lines were cut in F1. Review (#118) | [9716](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=9716) | @lutetiensis  |
|B| Review (#119)  | [9892](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=9892) | @lutetiensis |
|C| Review (#117) | [9930](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=9930) | @lutetiensis |
|D| Needs smoothing, F1 & F2 don't exist | [9928](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=9928) | @lutetiensis |
|E| To do | [9694](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=9694) | @lutetiensis |
|F| ✓ | [10661](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=10661) | |
|G| ✓ | [10511](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=10511) | |
|H| To do | [10138](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=10138) | @georgd |
|I| To do | [10683](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=10683) | TBD |
|J| To do | non-existent | TBD |
|K| To do | non-existent | TBD |
|L| Needs smoothing | [9669](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=9669) | TBD |
|M| Review (#120) | [10644](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=10644) | @astoeriko |
|N| Needs smoothing | [10512](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=10512) | @lutetiensis |
|O| ✓ | [9679](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=9679) | |
|P| To do | [10697](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=10697) | TBD |
|Q| Needs smoothing | [9796](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=9796) | TBD |
|R| To do | [10168](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=10168) | TBD |
|S| To do | [10033](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=10033) | @astoeriko|
|T| ✓ | [9739](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=9739) | |
|U| To do | non-existent | TBD |
|V| ✓ (#114) | [9737](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=9737) | |
|W| To do | non-existent | TBD |
|X| To do | non-existent | TBD |
|Y| To do | non-existent | TBD |
|Z| To do | non-existent | TBD |

**Comment by lutetiensis** [comment]
JKUWXYZ initials don't exist, but the letters could be borrowed from's [Dürer's capital letters](http://www.ponticulus.hu/britannicus/durer-abc.html).

**Comment by bt2901** [comment]
This link does not have JUW.

**Comment by bt2901** [comment]
I think the J from [this page](https://www.fromoldbooks.org/Search/?kw=letterj) comes close:
![image](https://user-images.githubusercontent.com/3958256/104388953-73e18600-554b-11eb-87dc-0c5502305559.png)

**Comment by georgd** [comment]
> JKUWXYZ initials don't exist, but the letters could be borrowed from's [Dürer's capital letters](http://www.ponticulus.hu/britannicus/durer-abc.html) which seem very close.

I’m sorry, but the Dürer letters are a different style, created almost 100 years earlier, still closer to calligraphic writing than the Garamond style letters.

> I think the J from [this page](https://www.fromoldbooks.org/Search/?kw=letterj) comes close:
> ![image](https://user-images.githubusercontent.com/3958256/104388953-73e18600-554b-11eb-87dc-0c5502305559.png)
> 
> ETA: or from here https://www.fromoldbooks.org/Various-InitialLetters/pages/alphabets-18thc-amsterdam-155/

 Both of them are even further away from the Garamond style than Dürer's. Although I hate to say it, I’m quite confident that we won’t find a good drop-in for JKUWXY and that they will have to be drawn from scratch. A tiny chance might exist for Z but it’s not very probable.

**Comment by lutetiensis** [comment]
> > JKUWXYZ initials don't exist, but the letters could be borrowed from's [Dürer's capital letters](http://www.ponticulus.hu/britannicus/durer-abc.html) which seem very close.
> 
> I’m sorry, but the Dürer letters are a different style, created almost 100 years earlier, still closer to calligraphic writing than the Garamond style letters.

You're right, but that could serve as a base if we intend to create the missing initials. :)

**Comment by georgd** [comment]
Oh, the letters themselves are not the issue for me. I have sources for most of them and I'm capable of drawing the missing ones. It's the ornament what I'm struggling with.

**Comment by bt2901** [comment]
I see, the ornaments are indeed difficult to imitate. Could something from [Historic design in printing](https://archive.org/details/historicdesignin00john) serve as inspiration?

**Comment by bt2901** [comment]
After some thought, I think that initials by William Morris could be a good fit. 

These designs should be public domain, e.g. see https://freesvg.org/william-morris-letter-i 
I was unable to find all letters collected in a single place with proper attribution, but it appears that this website got them all as font: https://www.dafont.com/goudy-initialen.font
And this one provides them as SVG: https://pixabay.com/vectors/alphabet-english-font-vintage-4244798/

That's my super quick and dirty mock-up of what would initials look like if added to the current font. It is obvious that the design should be significantly simplified, but the ornamental elements (curved lines, leaves, and flowers) and overall shape seem consistent with EB Garamond.

![image](https://user-images.githubusercontent.com/3958256/104465355-040fe180-55c5-11eb-8fa1-20b5c06630aa.png)

**Comment by lutetiensis** [comment]
@georgd I haven't abandonned this. My computer died a month ago and I cannot work on this anymore... for now...
