### ISSUE TITLE
About Google Fonts version

### ISSUE THREAD

**Issue by NightFurySL2001** [georgd/EB-Garamond#116]
I would like to ask about Google Fonts have uploaded a variable font version of this font but it doesn't seem to be on here. What's with the [variable version on Google Fonts](https://fonts.google.com/specimen/EB+Garamond)?

> In November 2019, the family has been updated to a variable font family.

**Comment by mikkelee** [comment]
I believe Google's version is Octavio Pardo's reworking of Duffner's work

https://github.com/octaviopardo/EBGaramond12 (see AUTHORS.txt/CONTRIBUTORS.txt for Duffner credit)

**Comment by NightFurySL2001** [comment]
Ok, thank you.
P/S: Github did provide an download area: [Releases](https://github.com/georgd/EB-Garamond/releases). You can throw a zip file of otf/ttf files in there and it'll be a much less chore to go to other site to download the font files.
> Due to Github deciding not to provide a download area any more
