### ISSUE TITLE
greek letter phi(φ) looks bad

### ISSUE THREAD

**Issue by Firestar-Reimu** [georgd/EB-Garamond#127]
The opening of the letter is too small, especially in the italic mode

![图片](https://user-images.githubusercontent.com/65082432/137618844-61cf6aab-abc0-41c9-9fb3-c4d3c5bcb150.png)

**Comment by dpk** [comment]
<img width="605" alt="Screenshot 2021-11-07 at 14 29 23" src="https://user-images.githubusercontent.com/378375/140647100-47c333da-ff95-4eb7-8bbd-7adc9fea1eca.png">

I happen to think the open style looks better in this context, but both styles are valid.

**Comment by Firestar-Reimu** [comment]
![Screenshot_20211107_213609](https://user-images.githubusercontent.com/65082432/140647312-172b18ae-3b55-4276-8acc-d873e8cb7e2b.png)

@dpk I found that the opened and closed phi has been put wrong in your comment

**Comment by dpk** [comment]
The screenshot I posted is how your comment renders on my computer, exactly reversed from how you say they ‘should’ look. The WP page you cite says nothing about open vs closed designs for the alphabetical vs symbolic character codepoints.

> It is necessary to distinguish these, as one may not recognize this letter is a phi

As a relatively fluent reader of the Greek alphabet, I can say with confidence that I would recognize both quite clearly as phi. It is as irrelevant to the recognizability of the character as whether Latin a and g have two storeys or one.

I think this issue should be closed as ‘won’t fix’.

**Comment by georgd** [comment]
The design of the Greek glyphs is based on the original Garamond ones. The distinctive feature that differentiates the two variants is not the openness of the left bow but the overall construction: the one the OP wishes to show an open bow is drawn in one curly stroke which inhibits an ascender while the other is constructed from a circle and a straight line, with the latter forming an ascender and a descender.
