### ISSUE TITLE
Tu ligature missing?

### ISSUE THREAD

**Issue by rdtennent** [georgd/EB-Garamond#129]
Tabby Testy Timid Torpor Truck Turtle Twitter Typo

Reported to me by John Sidles <jasidles@gmail.com>.

\documentclass{standalone}
\usepackage[T1]{fontenc}
\RequirePackage{ebgaramond}
\begin{document}
\begin{tabular}{l}
Tabby\\Testy\\Timid\\Torpor\\
Truck\\Turtle\\Twitter\\Typo
\end{tabular}
\end{document}

**Comment by georgd** [comment]
Sorry for the late answer. This is not about ligatures but about kerning, I suppose (the code in the example doesn’t compile, as expected from visual analysis, some whitespace must have gone lost). There definitely shouldn’t be any ligature in play here. But I can confirm that the kerning isn’t applied that should be present. The opentype font does contain the Tu kern pair (together with Tm, Tn, T<dotlessi> and similar). This must have gone lost somewhere between the OT font and the T1 version.

**Comment by rdtennent** [comment]
Georg:  The bad spacing for Tu also arises when using xelatex or lualatex (which embed the OTF).

**Comment by georgd** [comment]
OK, just tried with lualatex and got this with Tu and Tr kerned as expected:

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/214002/226130051-1979ba95-e203-48e6-8c8f-c30df08dc9c7.png">

**Comment by rdtennent** [comment]
That's not the spacing I get using lualatex and EBGaramond in latest TeXLive.  
[test.pdf](https://github.com/georgd/EB-Garamond/files/11009454/test.pdf)

**Comment by rdtennent** [comment]
Here is the version information in EBGaramond-Regular.otf in TeXLive2023:

Version 1.000;PS 001.000;hotconv 1.0.88;makeotf.lib2.5.64775

**Comment by rdtennent** [comment]
I believe the TeXLive fonts are from 

https://github.com/octaviopardo/EBGaramond12/

**Comment by rdtennent** [comment]
I've submitted an issue report here:

https://github.com/octaviopardo/EBGaramond12/issues/46
