### ISSUE TITLE
Ligatures not automatically working with German

### ISSUE THREAD

**Issue by AtrusRiven** [georgd/EB-Garamond#130]
It seems to me that ligatures which work well with English do not work with German. Is this a feature still missing or do I have to adjust something extra? The only workaround is to replace the ligatures manually. The difference in the Screenshot below is simply the language assigned to the text. The Software I work with is LibreOffice (Version 7.1.7, but it seems to generally apply). Thanks for hints!
![Screenshot](https://user-images.githubusercontent.com/29101440/143487725-5284f51d-27cc-410a-bf07-92facb580548.png)

**Comment by georgd** [comment]
This is probably done with the Googlefonts variant. There, the German f-ligatures implementation is broken. I have to close this issue in this repository as it’s not valid here.
