### ISSUE TITLE
Download of Recent Compilations

### ISSUE THREAD

**Issue by oghaki** [georgd/EB-Garamond#141]
I have two questions related to compiled versions:

1. Is there anywhere I can download recent compilations (e.g., a nightly compilation or otherwise that is more recent than the versions from the Release section or BitBucket equivalent)?  
2. If the answer № 1 is 'No', can you tell me where I can find the most up-to-date TTF or OTF download?  I've reviewed [the website](http://www.georgduffner.at/ebgaramond/) and [GitHub](https://github.com/georgd/EB-Garamond) / [BitBucket](https://bitbucket.org/georgd/eb-garamond/src/master/) repos, but I wasn't sure whether all of the info was up-to-date and consistent, and I'm not very familiar with Fontforge and wasn't sure how involved it would be to try to compile it myself.  I also noticed mention of [octaviopardo's repo](https://github.com/octaviopardo), but I've noticed more recent commits here.

P.S., Thanks for this project—I first downloaded the release version of these years ago, and I have always loved the idea of what you're doing.

**Comment by timgrei** [comment]
[EBGaramond.zip](https://github.com/georgd/EB-Garamond/files/10832850/EBGaramond.zip)

**Comment by oghaki** [comment]
Thank you very much @timgrei

**Comment by MrSpinalzo** [comment]
> [EBGaramond.zip](https://github.com/georgd/EB-Garamond/files/10832850/EBGaramond.zip)

Where does this come from? Did you compile it yourself?

**Comment by ArchangeGabriel** [comment]
> > [EBGaramond.zip](https://github.com/georgd/EB-Garamond/files/10832850/EBGaramond.zip)
> 
> Where does this come from? Did you compile it yourself?

I guess so since they have been working on this repository lately.

However please note that outside Initials/Lettrine, the version from @octaviopardo is much more up-to-date.

**Comment by MrSpinalzo** [comment]
Where can I download that version?

**Comment by ArchangeGabriel** [comment]
Here: https://github.com/octaviopardo/EBGaramond12/tree/master/fonts

**Comment by MrSpinalzo** [comment]
Thanks!

**Comment by timgrei** [comment]
It's really not that hard to build. You run the makefile. It then probably tells you that you are missing some software. You install those. Run again. Done.

**Comment by MrSpinalzo** [comment]
I've tried to run the makefile, but my PC doesn't tell me what software I've got to install to make it work. How did you run it?

**Comment by timgrei** [comment]
What does it say?

**Comment by doctorlard** [comment]
This is on Ubuntu 20.04, using (apt-get installed) fontforge version 20201107:
```
$ make 
Generating	build/EBGaramond08-Regular.otf
Traceback (most recent call last):
  File "/home/johnno/Projects/EB-Garamond/tools/makefont.py", line 11, in <module>
    import fontforge
ModuleNotFoundError: No module named 'fontforge'
make: *** [Makefile:46: build/EBGaramond08-Regular.otf] Error 1
```

**Comment by timgrei** [comment]
You need the Ubuntu package fontforge and python3-fontforge.

**Comment by timgrei** [comment]
If it's not in the apt sources, you can use pip.

**Comment by doctorlard** [comment]
Hah. Perhaps that could go in the README. shall I do a PR? Also, I tried `pip install fontforge` which didn't work.

**Comment by timgrei** [comment]
Huh, you're right. It's not in the pypi. You could do a PR with an installation guide, I'm sure @georgd will accept that. It's not that obvious for non-coders.

**Comment by doctorlard** [comment]
Happy to do that; I'll make a separate issue. I'll have to figure out what magic is being done to produce the `python3-fontforge` package first though, because what on earth is this:
```
/usr/lib/python3/dist-packages/fontforge.cpython-310-x86_64-linux-gnu.so
```

**Comment by timgrei** [comment]
The path to the module. What's wrong with that?

**Comment by doctorlard** [comment]
Well, that's all that `python3-fontforge` installs (aside from docs and examples). So it's all very well for Ubuntu folks to go `sudo apt install fontforge python3-fontforge && make` job done, but without it being in PyPI a user would presumably have to install fontforge, but also build the cpython binary and stick it in the Python include path. I am not at all familiar with installing Fontforge on Windows or Mac, so I don't know if this bit is included or not. I can write the bit for Ubuntu though, so I suppose I can always start a PR with that.

**Comment by timgrei** [comment]
> Well, that's all that `python3-fontforge` installs (aside from docs and examples). So it's all very well for Ubuntu folks to go `sudo apt install fontforge python3-fontforge && make` job done, but without it being in PyPI a user would presumably have to install fontforge, but also build the cpython binary and stick it in the Python include path. I am not at all familiar with installing Fontforge on Windows or Mac, so I don't know if this bit is included or not. I can write the bit for Ubuntu though, so I suppose I can always start a PR with that.

I don't know either. But a quick Google search makes it seem like it really is a problem for Windows users.

**Comment by doctorlard** [comment]
Heh, agreed.. let's discussion/ideas etc. to the new issue, #142

**Comment by timgrei** [comment]
Looks like you would need to change the PYTHON?=python to =ffpython

**Comment by timgrei** [comment]
@MrSpinalzo, let's do this here. What OS are you on?

**Comment by MrSpinalzo** [comment]
I use Windows.
