### ISSUE TITLE
Where to download latest stable releases ? 

### ISSUE THREAD

**Issue by medmedin2014** [georgd/EB-Garamond#150]
I really love this font, and I thank all people who worked hard to give us this treasure, the problem is that the only official release dates from [2014](https://bitbucket.org/georgd/eb-garamond/downloads/) ! Where can we download more recent stable versions ? Is the [nightly](https://github.com/georgd/EB-Garamond/releases/) build safe to use in production ?

**Comment by georgd** [comment]
The latest “stable” release is indeed the one from 2014. I’m slowly getting on with the project again. The latest nightly contains the recently completed Initials and some changes to features in EBG12-Re, which I haven’t documented yet.

**Comment by medmedin2014** [comment]
Thanks for this great project ;)
