### ISSUE TITLE
Italics: "Quis" ligature with "Qui" and "is" ligatures

### ISSUE THREAD

**Issue by Alexander-Wilms** [georgd/EB-Garamond#155]
```tex
% !TeX program = lualatex
\documentclass{standalone}
\usepackage[]{fontspec}
\setmainfont{EBGaramond}[
UprightFeatures={
	SizeFeatures={
		{Size={12-},Font=*12-Regular},
		{Size={-12},Font=*08-Regular}
}},
ItalicFeatures={
	SizeFeatures={
		{Size={12-},Font=*12-Italic},
		{Size={-12},Font=*08-Italic}
}}]
\begin{document}
\textit{
	Quis\quad
	Qui s\quad
	Qu is\quad
	Qui \kern-5.39ptis
	|
	\large
	Quis\quad
	Qui s\quad
	Qu is\quad
	Qui \kern-6.4ptis}
\end{document}
```

![image](https://user-images.githubusercontent.com/3226457/226210179-2f2586fc-bdba-47e7-83a2-4f25a68d6c6f.png)

![image](https://user-images.githubusercontent.com/3226457/226196485-65ac6fa8-46ee-474f-9305-fb618efcc0a7.png)

**Comment by Alexander-Wilms** [comment]
Hm, the example still does not work for me.

**Comment by georgd** [comment]
Well, the feature has to be merged to the font which is currently hindered by some half done work from six years ago. I’m working on this.

**Comment by georgd** [comment]
Now it is. But I fear, I broke the cap diacritics.

**Comment by georgd** [comment]
Ok, I didn’t :)

**Comment by Alexander-Wilms** [comment]
Yep, now it works!
