### ISSUE TITLE
Italic: Add Top Half Brackets

### ISSUE THREAD

**Issue by amarakon** [georgd/EB-Garamond#171]
The top left and right half brackets (`U+2E22` and `U+2E23` respectively) are present in the roman font but missing from the italic font. Can you add them?

**Comment by georgd** [comment]
Would you want them upright in the italics as well?

**Comment by amarakon** [comment]
They should be slanted just like regular brackets (*`[]`*) are. However, issue #170 means it should also be able to be used unslanted in italics if the user wishes.

**Comment by georgd** [comment]
Unslanted versions (and importantly their kerning) won't be added in the 0.0 branch. That’s too much work that would need to be done anew for the v1+ branch. Speaking of which, I haven’t kerned these half brackets either yet.

**Comment by amarakon** [comment]
If I'm not mistaken, half brackets are just regular brackets with the bottom cut off. Does that mean you can copy the kerning from the regular brackets to the half brackets? Or does the bottom half of brackets also have to be taken into account for kerning?

**Comment by georgd** [comment]
When kerning you need to take into account the entire glyph. The top half left bracket allows a following letter without an ascender on the left side (e.g. a, d, x etc.) to glide a tiny bit more under the bracket than the normal bracket does. However, I wouldn’t expect a big effect. It has to be checked nevertheless.
