### ISSUE TITLE
Add Half Ring Characters to Italic Fonts

### ISSUE THREAD

**Issue by amarakon** [georgd/EB-Garamond#178]
Can you add *modifier letter right half ring* (`U+02BE`) and *modifier letter left half ring* (`U+02BF`) to the italic fonts?

**Comment by georgd** [comment]
These are already present.

**Comment by amarakon** [comment]
Sorry, I did not realize they are present in EB Garamond 12 Italic. However, they are still not present in EB Garamond 08 Italic.

**Comment by amarakon** [comment]
Can you consider reopening this issue? The half ring characters are not present in EB Garamond 08 Italic.

**Comment by georgd** [comment]
This might have been the last update to the EBG08 fonts for a longer time. I want to complete the merge first and then get the italics on par with the roman.
