### ISSUE TITLE
Many letters suffer from wrong outlines

### ISSUE THREAD

**Issue by medmedin2014** [georgd/EB-Garamond#187]
I can't finish inspecting all letters, but here are some examples:

![path7148](https://github.com/georgd/EB-Garamond/assets/7027319/b6bea1b7-5815-4799-baf4-5a41f907df9c)

**Comment by georgd** [comment]
That’s right, but I won’t fix them in this version of the font. Octavio did already clean up these outlines and by merging the two versions, the issue should be gone.
