### ISSUE TITLE
Interpolation problems in `EBGaramond[wght].ttf`

### ISSUE THREAD

**Issue by behdad** [georgd/EB-Garamond#201]
Hello!

This is an automatically-generated report about possible interpolation problems in `EBGaramond[wght].ttf`, as found in the Google Fonts catalog.

To download a PDF version of this report with helpful visuals of the problems, click [here](https://github.com/behdad/google-fonts-ofl-interpolatable-results/raw/0d437489ad1b554f348b29a8b42bdd37b59dc933/reports/EBGaramond%5Bwght%5D.ttf.pdf); Or to view it on the GitHub website, click [here](https://github.com/behdad/google-fonts-ofl-interpolatable-results/blob/0d437489ad1b554f348b29a8b42bdd37b59dc933/reports/EBGaramond%5Bwght%5D.ttf.pdf).

The report follows:
```
Glyph Sigma was not compatible:
  Masters: '', 'wght=800.0':
    Contour 0 has a kink at 68: '', 'wght=800.0'
Glyph sigma was not compatible:
  Masters: '', 'wght=800.0':
    Contour 0 has a kink at 36: '', 'wght=800.0'
Glyph uni027B was not compatible:
  Masters: '', 'wght=800.0':
    Contour 0 has a kink at 17: '', 'wght=800.0'
Glyph uni028A was not compatible:
  Masters: '', 'wght=800.0':
    Contour 0 has a kink at 14: '', 'wght=800.0'
Glyph uni04A8 was not compatible:
  Masters: '', 'wght=800.0':
    Contour 0 has a kink at 40: '', 'wght=800.0'
Glyph uni1EFC was not compatible:
  Masters: '', 'wght=800.0':
    Contour 0 has a kink at 58: '', 'wght=800.0'
```

This report was generated using the `fonttools varLib.interpolatable` tool.  We understand that sometimes the tool generates false-positives.  Particularly for more complicated font designs.  If you did not find this report useful, please accept our apologies and ignore / close it.

To give feedback about this report, please file an issue or open a discussion at [fonttools](https://github.com/fonttools/fonttools).

Please note that I am doing this as a community service and do not represent Google Fonts.

**Comment by ethanc8** [comment]
@behdad I believe the version of EB Garamond on Google Fonts is based on Octavio Pardo's fork. You might want to report it to https://github.com/octaviopardo/EBGaramond12/tree/master, but it's currently unmaintained.

**Comment by behdad** [comment]
Thanks. The Google Fonts repository metadata was pointing here so my tools filed here. Looks like the metadata issue has been fixed since.
