### ISSUE TITLE
Errors or ambiguities found in Specimen.tex

### ISSUE THREAD

**Issue by Tchiller** [georgd/EB-Garamond#59]
I am just checking out that fantastic font and would like to thank you in the first place. 

Today I had a look at the Specimen document and would like to post some things, I stumbled onto. Sorry, it will be quite an unsorted list, but maybe some stuff is very easy to fix:
- you are loading +tlig. What is that. Not mentioned in the document. Maybe put a comment in the source
- 2.1 Locals: for english and german you could maybe link to the package selnolig. Your feature works but does seperate ligatures in too many cases
- 2.1 when separating the ligature fl (e.g. auflachen), the two letters touch each other
- 2.2 Character Composition and Decomposition: Some examples would be nice, especially as you load ccmp by default.
- 2.8 Contextual Alternates: does "should be on by default" mean, that you recommend it? I didn't get it when reading it first time. Sounds a bit like: "is switched on, if feature already works in this version". As you notice, I'm no native, so maybe just a "problem" for me
- 2.8 IRAQ - the R and A are touching each other
- 2.10.2 General Variants:
  - cv05: I can't see any differences. Please describe further!
  - cv06: Can't see any difference either. Maybe because you set cv06 in your preamble

OK, that's all I have noticed. Sorry for that messy list. But maybe it is some help. In my opinion, the Specimen.pdf is a great show case, so everything should be clear.

**Comment by PanderMusubi** [comment]
In Specimen.tex it says that dlig is not switched on by default. However, it looks that it is and therefore needs an asterisk in the caption of `\paragraph*{Discretionary Ligatures}` Correct?

**Comment by georgd** [comment]
@PanderMusubi, Iʹm not sure if I understand correctly. `liga` and `clig` should be enabled by default, but `dlig` and `hlig` shouldn’t, according to the specs. XeTeX does so, therefore if you look at the source, you’ll see that I had to use `\addfontfeature` in both cases.
