### ISSUE TITLE
kerning f + egrave in roman font

### ISSUE THREAD

**Issue by markvanatten** [georgd/EB-Garamond#74]
![kerntest](https://cloud.githubusercontent.com/assets/5402908/9658733/d5913f34-524b-11e5-92d6-69aa7d8dfb24.jpg)

The pair f è in the roman font seems to need correction. Without it, the space between them
almost breaks up the word; see the top word in the image. Switching off kerning altogether locally
by
{\addfontfeature{Kerning=Off}réfère}
yields the bottom word and looks much better to me.
See also the example `auffällig' on p.31 of Jost Hochuli's nice little book
Das Detail in der Typografie, 2nd ed., 2011. He, too, prefers
to let the letters touch in this case.

As a global solution, I use

\usepackage{filecontents}

\begin{filecontents_}{kernegrave.fea}
languagesystem DFLT dflt;
languagesystem latn dflt;
feature kern {
pos f egrave -1;
} kern;
\end{filecontents_}

\usepackage{fontspec}
\defaultfontfeatures{FeatureFile=kernegrave.fea}

**Comment by twardoch** [comment]
There is the glyph "f.short", and I would recommend to use it in such situations.

**Comment by markvanatten** [comment]
Thank you for the hint!

\documentclass[12pt]{article}

\usepackage{filecontents}

\begin{filecontents*}{kernegrave.fea}
languagesystem DFLT dflt;
languagesystem latn dflt;
feature  fegr {
	substitute	f' egrave by f.short;
} fegr  ;
\end{filecontents*}

\usepackage{fontspec}%
\defaultfontfeatures{FeatureFile=kernegrave.fea,RawFeature=+fegr}
\setmainfont{EB Garamond}
\begin{document}
réfère
\end{document}
![kerntest2](https://cloud.githubusercontent.com/assets/5402908/9664355/7913b41c-5269-11e5-9dbc-83f75dbedf97.jpg)

**Comment by uomoinverde** [comment]
Should this workaround be added to the font specimen?

**Comment by georgd** [comment]
Thank you for the report.
What Adam pointed out would be exactly my response to the question but I’d
recommend to enable the contextual alternates feature generally. It will
prevent other collisions as well.
I suppose, you are using LuaLaTeX which doesn’t activate it automatically
whereas XeLaTeX does so. To activate contextual alternates add
\defaultfontfeatures{RawFeature=+calt}
I think of adding a remark about it in the specimen.

2015-09-04 11:13 GMT+02:00 Filippo De Bortoli <notifications@github.com>:

**Comment by markvanatten** [comment]
Indeed, I am using lualatex.

Thanks to all for your remarks, and most of all, thank you Georg Duffner for EB Garamond!
