### ISSUE TITLE
U+202F Narrow No-Break Space missing

### ISSUE THREAD

**Issue by gandaro** [georgd/EB-Garamond#80]
At the moment EB Garamond does not seem to support it, but it should be easy to add.

Unicode 8.0 has the following to say about the character:

> U+202F NARROW NO-BREAK SPACE (NNBSP) is a narrow version of U+00A0 NO-BREAK SPACE, which except for its display width behaves exactly the same in its line breaking behavior. It is regularly used in Mongolian in certain grammatical contexts (before a particle), where it also influences the shaping of the glyphs for the particle. In Mongolian text, the NNBSP is typically displayed with <sup>1</sup>&frasl;<sub>3</sub> the width of a normal space character. The NNBSP can be used to represent the narrow space occurring around punctuation characters in French typography, which is called an “espace fine insécable.”

I guess, because EB Garamond cannot be used for Mongolian text anyway, it should mainly work well with Latin scripts. German also has a use for this character by the way: in abbreviations like “z. B.” or “i. d. R.” there are not supposed to be line breaks, but the spaces should be thin. I don’t know how thin exactly though.

**Comment by ArchangeGabriel** [comment]
Note that `\,` does not produce a NNBSP indeed, however directly putting one « » does work apparently.

**Comment by gandaro** [comment]
It does not work for me; I am also not using LaTeX.

**Comment by georgd** [comment]
I’m not sure if this glyph should belong to the font. Usually spaces are added by the typesetting program without paying respect to the space glyph in the font.

@gandaro do you currently use a font where this works as you expect?

**Comment by gandaro** [comment]
Well, I tested it in LibreOffice Writer, Firefox and Chrome, and in all of them using U+202F together with EB Garamond in ragged right text produced spaces of a length equal to that of the regular space character (U+0020). Using other fonts, e. g. Linux Libertine or DejaVu Sans, U+202F produced narrower spaces.

#### EB Garamond
![Example of usage of different space characters / EB Garamond](https://cloud.githubusercontent.com/assets/811907/12105660/1d128f68-b357-11e5-9417-2eabf45f641c.png)
#### Linux Libertine
![Example of usage of different space characters / Linux Libertine](https://cloud.githubusercontent.com/assets/811907/12105670/309a52f0-b357-11e5-92e7-a39bdc123495.png)

**Comment by gandaro** [comment]
But even using fonts that definitely do not have built-in support for U+202F (badly made free fonts from the Internet) these software packages produce narrower spaces for U+202F.

On the other hand, using the Junicode font it also creates spaces equal to those of U+0020…

**Comment by ArchangeGabriel** [comment]
I’m quite positive this has to be in the font now: I’ve just tried EB Garamond in Scribus, and I have a missing-char-in-font square instead of a Narrow No-Break Space. It works correctly with other fonts providing this character like Linux Libertine for instance.

**Comment by MRoth1910** [comment]
I'd like to bump this up in case anyone is still willing to take a crack at this. This is essential for correctly printing French and reproducing texts which use at least some conventions of French punctuation; ecclesiastical/liturgical Latin printing from the first half of the 20th century, for example, sometimes uses a space between the colons and the surrounding words just like in French. 

A regular nonbreaking space is better than nothing, but U+202F is incorporated into other free fonts that I have as noted by others way back in 2016.

**Comment by kenmcd** [comment]
> 
> 
> I'd like to bump this up in case anyone is still willing to take a crack at this. This is essential for correctly printing French and reproducing texts which use at least some conventions of French punctuation; ecclesiastical/liturgical Latin printing from the first half of the 20th century, for example, sometimes uses a space between the colons and the surrounding words just like in French.
> 
> A regular nonbreaking space is better than nothing, but U+202F is incorporated into other free fonts that I have as noted by others way back in 2016.

Do you have some examples of fonts which do get this right?
I am wondering what the "best" width is supposed to be.

The OpenType specs discuss it here: 
[https://docs.microsoft.com/en-us/typography/develop/character-design-standards/whitespace](https://docs.microsoft.com/en-us/typography/develop/character-design-standards/whitespace) 

"**Thin space U+2009** - Standard setting is 1/5 of the em space. 410 units in a 2048 unit per em font. This should be language dependent. The standard language dependent setting for French is 1/8 of the em space. 256 units in a 2048 unit per em font.
_Note :_ When traditionally typesetting the French language a word space is inserted before or after several punctuation characters. These characters are colon, semi colon, question, exclamation, right guillemets, and left guillemets. Commonly the preferred word space used is a thin space of 1/8 the em. Some French typographers prefer to use a larger space character of 1/4 the em with the colon and some other punctuation characters. OpenType supports character substitution and language dependant variants."

So their rule-of-thumb is 1/8 of the em space.

I will look at some other fonts to see what they have done, but I would like get some feedback from native French speakers/writers as to what it commonly looks like.

**Comment by ArchangeGabriel** [comment]
@kenmcd We indeed use two different spaces, your quoted text does not follow the rules of the *Imprimerie française*. It’s a thin space of 1/8 of the em before ; ? !, but a normal word space, although non-breaking, in front of : and inside « and ».

**Comment by kenmcd** [comment]
> 
> 
> @kenmcd We indeed use two different spaces, your quoted text does not follow the rules of the _Imprimerie française_. It’s a thin space of 1/8 of the em before ; ? !, but a normal word space, although non-breaking, in front of : and inside « and ».

Thanks!
Where can I find this "_Imprimerie française_" ?
I did a lot of searching, but the terms seem to be a bit generic.

**Comment by ArchangeGabriel** [comment]
The full title is « Lexique des règles typographiques en usage à l'Imprimerie nationale », you can see a cover below:
![Lexique-des-règles-typographiques-en-usage-à-lImprimerie-nationale](https://user-images.githubusercontent.com/490531/141142823-b41ec792-98bb-4023-a551-cb9131baa0cd.jpg)
Apparently they have been some PDF versions circulating on the internet, but they all seem offline now. But I can make a scan of the « Ponctuation » entry for you if you want.

**Comment by kenmcd** [comment]
Based on my searches that is a very popular book.
But I could not find a PDF anywhere.
Found a few things which cited it as a reference source.

> But I can make a scan of the « Ponctuation » entry for you if you want.

That would be fantastic. Thank you.

**Comment by ArchangeGabriel** [comment]
Here you go:
![image 4Q39B1](https://user-images.githubusercontent.com/490531/141650231-d16d5d45-b67e-4fd1-b4fb-7003a4d68f10.png)

**Comment by kenmcd** [comment]
> Here you go:

Thank you!

**Comment by ArchangeGabriel** [comment]
LaTeX is now complaining about that: `Missing character: There is no   (U+202F) in font [EBGaramond-Regular.otf]`.

**Comment by ArchangeGabriel** [comment]
Indeed, because that’s the one now provided by CTAN: https://ctan.org/tex-archive/fonts/ebgaramond. Will there be changes in this regard? Is your version going to be the main one again? And if so will you merge his bold version into it? I’ve seen there has been a lot of activity around this repo lately but couldn’t read all the backlog yet, so I might have missed an information.

**Comment by georgd** [comment]
> Indeed, because that’s the one now provided by CTAN: https://ctan.org/tex-archive/fonts/ebgaramond. Will there be changes in this regard? Is your version going to be the main one again? And if so will you merge his bold version into it? I’ve seen there has been a lot of activity around this repo lately but couldn’t read all the backlog yet, so I might have missed an information.

I’m going to merge the two versions. In general, I’ll keep Octavio’s work but re-add what got lost feature-wise and change some designs where I’m not happy (like the ball terminal on Q.long). Later, I plan to integrate the EBG08 fonts in the variable axis system.

**Comment by ArchangeGabriel** [comment]
Awesome news! Glad to see that EB Garamond is still very alive. :)

**Comment by MRoth1910** [comment]
> > LaTeX is now complaining about that: `Missing character: There is no   (U+202F) in font [EBGaramond-Regular.otf]`.
> 
> EB Garamond 12 Regular already has this glyph. Your finding must be about Octavio Pardo's version. I'm adding it to EBG12 Italic right now.

Hmm, at least when I commented, I don't know if that was clear — since no action had been taken as of 2016. But you're saying that it does now?

**Comment by georgd** [comment]
Yes, it's in the nightly build.
