### ISSUE TITLE
italic small caps?

### ISSUE THREAD

**Issue by ousia** [georgd/EB-Garamond#81]
@georgd, I wonder whether it would be possible that the next release could include small cap glyphs for the italic font.

Congratulations for your excellent work on this typeface.

**Comment by georgd** [comment]
The italic font does contain small cap latin glyphs. Are you looking for greek sc glyphs?

**Comment by ousia** [comment]
@georgd, many thanks for your reply.

I’m afraid I’m not looking for Greek small cap glyphs.

One last question: do you plan to add small cap Latin glyphs to the italic font in the future?

**Comment by georgd** [comment]
The italic font already contains small cap latin glyphs! What application are you using where you don’t see them?

**Comment by ousia** [comment]
Sorry for misreading. I added _n’t_ to _does_ in “the italic font does contain small cap Latin glyphs”.

I use ConTeXt. But the version 0.15c from EBGaramond08-Italic.otf contains regular glyphs instead of italic ones for Latin small caps in the italic font.

I will have to wait until the next version is released.

Many thanks for your help.
