### ISSUE TITLE
Roman numerals

### ISSUE THREAD

**Issue by PanderMusubi** [georgd/EB-Garamond#84]
In order to get more experience and contribute to EB Garamond at the same time, I would like to start with something simple. I would like to add support for the Roman numerals as seen in http://unicode.org/charts/PDF/U2150.pdf
What is a good approach here? I can create uni2164.glyph and refer to glyph in _V.glyph and make a pull request for review. Would that be welcomed?

**Comment by PanderMusubi** [comment]
Ah, just found these glyphs in the repo after all. :stuck_out_tongue_closed_eyes: Perhaps there is some other work to get started with for me.

**Comment by georgd** [comment]
Hi Pander, thank you for your offer, that would be very welcomed!
