### ISSUE TITLE
Add support for Pāli latin letters with diacritics

### ISSUE THREAD

**Issue by jenstroeger** [georgd/EB-Garamond#89]
Perhaps an extension of https://github.com/georgd/EB-Garamond/issues/86.

It would be great to add the following latin characters with diacritics as used by the [Pāli](https://en.wikipedia.org/wiki/Pali) language:

```
U+00D1 Ñ U+00F1 ñ — Latin letter n with tilde
U+0100 Ā U+0101 ā — Latin letter a with macron
U+012A Ī U+012B ī — Latin letter i with macron
U+015A Ś U+015B ś — Latin letter s with acute
U+012A Ū U+012B ū — Latin letter u with macron
U+1E0C Ḍ U+1E0D ḍ — Latin letter d with dot below
U+1E24 Ḥ U+1E25 ḥ — Latin letter h with dot below
U+1E36 Ḷ U+1E37 ḷ — Latin letter l with dot below
U+1E40 Ṁ U+1E41 ṁ — Latin letter m with dot above
U+1E42 Ṃ U+1E43 ṃ — Latin letter m with dot below
U+1E44 Ṅ U+1E45 ṅ — Latin letter n with dot above
U+1E46 Ṇ U+1E47 ṇ — Latin letter n with dot below
U+1E5A Ṛ U+1E5B ṛ — Latin letter r with dot below
U+1E62 Ṣ U+1E63 ṣ — Latin letter s with dot below
U+1E6C Ṭ U+1E6D ṭ — Latin letter s with dot below
```

**Comment by carbeck** [comment]
These appear to be included already in the version from the Ubuntu repos, whose files date from October 2013:

![ebgar12](https://cloud.githubusercontent.com/assets/2134500/23405801/3c1e70ec-fdbc-11e6-96bc-72f0f2fcfd57.png)

**Comment by jenstroeger** [comment]
Oh then all is good. I didn’t see them in the [type specimen](https://github.com/georgd/EB-Garamond/blob/master/specimen/Specimen.pdf)...

Agreed on the dots though!

**Comment by jenstroeger** [comment]
Oh then all is good. I didn’t see them in the type specimen...

Agreed on the dots though!
